apiVersion: v1

kind: Service

metadata:
  name: cloudops-api
  namespace: cloudops

spec:
  selector:
    app: cloudops-api

  ports:
    - name: http
      port: 8000
      targetPort: 8000

  type: ClusterIP
